spring:
  application:
    name: book-service
  data:
    mongodb:
      uri: mongodb://root:example@host.docker.internal:27017/bookdb?authSource=admin

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka
  instance:
    prefer-ip-address: true
